### ISSUE TITLE
Keep comments option

### ISSUE THREAD

**Issue by leph83** [stylecow/stylecow#10]
Other minifiers have the option to keep comments by adding a ! to the comment.
e.g 
/*!
comment to keep when minified
*/

**Comment by oscarotero** [comment]
By default, there's two predefined code styles: normal and minify, you can see the full config here: https://github.com/stylecow/stylecow-core/blob/master/lib/coder.js#L219

You can create your own code style. If you see the `comments` key, it accepts thre values: all, important and none. `important` value keep these coments.

**Comment by leph83** [comment]
Ok, I see the setting but I have no idea, how to create my own code style. Is there a tutorial somehwere?
Would be nice to have another code style to choose in the stylecow.json or to have settings to pass to

**Comment by leph83** [comment]
I mean something like this for stylecow.json would be amazing
code: {
  "style": "minify",
  "comments": "important"
}

**Comment by oscarotero** [comment]
Done. I just published the `7.4.0` with support for custom style code.

**Comment by leph83** [comment]
> Done. I just published the `7.4.0` with support for custom style code.

You are amazing. I didn't expect, that you would implement it like I suggested, but I'm very happy, that I have to option to change that setting.
