### ISSUE TITLE
Use Chokidar instead of Gaze

### ISSUE THREAD

**Issue by ai** [stylecow/stylecow#4]
PostCSS’s `package.json` has `stylecow` in `devDependencies` for CSS parsers benchmarks. Unfortunately `gaze` from your dependencies doesn’t support io.js and node.js 0.12.

Riot.js had [a same issue](https://github.com/muut/riotjs/issues/149) and they just [change](https://github.com/muut/riotjs/commit/bf4c25510cffdd9045c6be9552478c8dd09d4bf0) `gaze` to [chokidar](https://github.com/paulmillr/chokidar) with a comment “Chokidar is awesome”.

Changes is very simple and `chokidar` lookslike better, that `gaze`. I can send PR, if you agree.

/cc @oscarotero

**Comment by oscarotero** [comment]
I'm not happy with gaze because of the slowness to create a new release that fixes some other issues like https://github.com/shama/gaze/issues/162. I was playing with chokidar and I see it as a good alternative, so I've release a new version with the change.

**Comment by ai** [comment]
Nice. Thanks for quick fix :).
